### ISSUE TITLE
Issues reproducing Cu-Mg example

### ISSUE THREAD

**Issue by npaulson** [PhasesResearchLab/ESPEI#45] opened 2017-12-18 22:51 UTC
I had several issues running the Cu-Mg example from the ESPEI website. I installed ESPEI using the conda command, and took the Cu-Mg data directory from the ESPEI-datasets repository.

I first tried reproducing the diagram from the section titled, **First-principles phase diagram**
The code successfully ran,  but the returned phase diagram didn't match the example well:
![diagram_dft](https://user-images.githubusercontent.com/6651068/34131733-768002fe-e412-11e7-8dff-39f08f876b0a.png)

I then tried reproducing the results in the **MCMC optimization** section. I wasn't able to successfully perform the MCMC optimization. The code returned numerous errors over the course of several minutes and eventually hung with no further output.

This file contains the full python output when I ran the optimization:
[espei_mcmc_error.txt](https://github.com/PhasesResearchLab/ESPEI/files/1569661/espei_mcmc_error.txt)

Here is my python version and installed packages/versions:
[python_info.txt](https://github.com/PhasesResearchLab/ESPEI/files/1569672/python_info.txt)

**Comment by bocklund** [comment] 2017-12-19 00:57
### DFT diagram

Hm. The phase diagram looks almost to what I would expect, except the single phase data for the Laves phase seems like it was not fit. Are there any parameters in the TDB for the Laves phase? If so, what are the values?

To try to debug the fitting steps, you could try to up the verbosity by changing your input file to include the `verbosity` key. Values are 0 (default) for warnings, 1 for info, 2 for debug level logging. The input file would look like:

```yaml
system:
  phase_models: Cu-Mg-input.json
  datasets: input-data
generate_parameters:
  excess_model: linear
  ref_state: SGTE91
output:
  output_db: cu-mg_dft.tdb
  verbosity: 2
```
(see http://espei.org/en/latest/writing_input.html for a reference on all the input file keys/values)

With the upped verbosity, you should be seeing something like in the attached file (this is only output for the Laves phase, I removed the other phases) [verbose-laves-phase.txt](https://github.com/PhasesResearchLab/ESPEI/files/1569899/verbose-laves-phase.txt). You should be getting the exact output as far as AIC values. If you aren't that means either your espei-datasets is out of date (I am on commit hash `a56379c28`, I made a fresh clone just now). Another source of error is possibly copying or typing the phase description incorrectly from the example. It should look like the following

```json
         "LAVES_C15": {
            "sublattice_site_ratios": [2, 1],
            "sublattice_model": [["CU", "MG"], ["CU", "MG"]]
         }
```

The parameters I generate for the Laves phase in the TDB are 

```

FUNCTION VV0004 1 46172.2; 10000 N !
FUNCTION VV0005 1 -10641.5; 10000 N !
FUNCTION VV0006 1 30748.4; 10000 N !
FUNCTION VV0007 1 20736.3; 10000 N !
FUNCTION VV0008 1 17766.4; 10000 N !
FUNCTION VV0009 1 150325.0; 10000 N !
FUNCTION VV0010 1 21243.0; 10000 N !
FUNCTION VV0011 1 214671.0; 10000 N !
... (other phases, functions, and parameters)

PHASE LAVES_C15 %  2 2 1 !
CONSTITUENT LAVES_C15 :CU,MG:CU,MG: !
... 

PARAMETER G(LAVES_C15,CU:CU;0) 1 3*GHSERCU# + VV0004#; 10000 N !
...

PARAMETER G(LAVES_C15,MG:MG;0) 1 3*GHSERMG# + VV0007#; 10000 N !
...

PARAMETER G(LAVES_C15,CU:MG;0) 1 2*GHSERCU# + GHSERMG# + VV0005#; 10000 N !
PARAMETER G(LAVES_C15,MG:CU;0) 1 GHSERCU# + 2*GHSERMG# + VV0006#; 10000 N !
PARAMETER L(LAVES_C15,CU:CU,MG;0) 1 VV0008#; 10000 N !
PARAMETER L(LAVES_C15,CU,MG:CU;0) 1 VV0009#; 10000 N !
PARAMETER L(LAVES_C15,CU,MG:MG;0) 1 VV0010#; 10000 N !
PARAMETER L(LAVES_C15,MG:CU,MG;0) 1 VV0011#; 10000 N !
```

### MCMC

The errors with running the MCMC optimization is actually a pycalphad issue. The short answer is that you need to remove the `gmpy2` package (see the [pycalphad installation troubleshooting](https://pycalphad.org/docs/latest/INSTALLING.html#typeerror-argument-is-not-an-mpz-during-a-calculation) docs for more info).

**Comment by npaulson** [comment] 2017-12-19 16:50
Thanks for your help

**DFT Diagram**

I ran ESPEI again per your instructions (and also removed the gmpy2 package), but I'm still getting the same incorrect phase diagram.

The verbose output, .tdb and input files seem to match what you are providing. I'll give links to these files if it's helpful.

[Cu-Mg-input.json.txt](https://github.com/PhasesResearchLab/ESPEI/files/1572342/Cu-Mg-input.json.txt)
[out_espei_dft.txt](https://github.com/PhasesResearchLab/ESPEI/files/1572330/out_espei_dft.txt)
[cu-mg_dft.tdb.txt](https://github.com/PhasesResearchLab/ESPEI/files/1572336/cu-mg_dft.tdb.txt)
[espei-in.yaml.txt](https://github.com/PhasesResearchLab/ESPEI/files/1572332/espei-in.yaml.txt)

This seems odd seeing that ESPEI is getting the parameters right.

**MCMC**

After removing the gmpy2 package I'm getting fewer error messages and things seem to be working correctly. 

The one thing I'm noticing is that each MCMC step is taking ~10 minutes on a four processor PC. Is this sort of performance on par with what you would expect? If so, I'll obviously need to run it on a cluster.

MCMC verbose output:
[out_espei_mcmc.txt](https://github.com/PhasesResearchLab/ESPEI/files/1572464/out_espei_mcmc.txt)

**Comment by bocklund** [comment] 2017-12-19 18:28
### DFT diagram

I was able to reproduce your issue. This was my fault. There was some data that got committed since I last checked the DFT diagram that had the sublattice site ratios flipped for the Laves phase. I have fixed it in espei-datasets with hash 9ed69cb6. You should be able to `git pull`, refit and verify that it works now.

### MCMC

The warnings you saw are expected behavior. It's probably time for us to silence those because they are confusing for everyone.

As far as the step time, that seems in the ballpark. Usually I've seen good convergence of the parameters to a minimum around 200-300 steps, so a cluster may be of interest if you have one. 

We support using MPI if you switch the scheduler to MPIPool. See the espei [FAQ](http://espei.org/en/latest/#q-can-i-run-espei-on-a-supercomputer-supporting-mpi) and input docs](http://espei.org/en/latest/writing_input.html#scheduler) for that.

**Comment by bocklund** [comment] 2017-12-19 18:28
Let me know if you were able to get it all working

**Comment by npaulson** [comment] 2017-12-19 19:46
**DFT diagram**
I downloaded the new data and the diagram looks much closer, but not exactly identical:
![diagram_dft_new](https://user-images.githubusercontent.com/6651068/34175702-f92cfa6c-e4c2-11e7-8b6a-94c00ba07219.png)

**MCMC**
Getting this onto the cluster may take a little while. I'll report back if I have difficulties.

Thanks for your help

**Comment by bocklund** [comment] 2017-12-19 19:59
Great! That's what it should look like. I added some mixing data from DFT since the original diagram was put on the website. I'm closing this for now then.

**Closed by bocklund** 2017-12-19 19:59 UTC
